ALTER TABLE Stay ADD INDEX idx_stay_customer_checkInTime (customerId, checkInTime);
ALTER TABLE Reservation ADD INDEX idx_reservation_roomtype_dates (roomTypeId, checkInDate, checkOutDate);
ALTER TABLE Room ADD INDEX idx_room_roomtype_status (roomTypeId, status);
ALTER TABLE Room ADD INDEX idx_room_floor (floor);
ALTER TABLE Bill ADD INDEX idx_bill_checkIn_paymentStatus_createdTime (checkInId, paymentStatus, createdTime);
ALTER TABLE Payment ADD INDEX idx_payment_bill_paymentTime (billId, paymentTime);
ALTER TABLE ConsumptionRecord ADD INDEX idx_consumption_checkin_time (checkInId, time);
ALTER TABLE ConsumptionRecord ADD INDEX idx_consumption_service_time (serviceId, time);
ALTER TABLE ConsumptionRecord ADD INDEX idx_consumption_product_time (productId, time);
ALTER TABLE Customer ADD INDEX idx_customer_membership_phone (membershipLevelId, phone);
ALTER TABLE Employee ADD INDEX idx_employee_department_position (department, position);
ALTER TABLE Maintenance ADD INDEX idx_maintenance_room_startTime (roomId, startTime);
ALTER TABLE RoomType ADD INDEX idx_roomtype_basePrice (basePrice);
ALTER TABLE Bill ADD INDEX idx_bill_totalAmount (totalAmount);
