class SqList:
    def __init__(self, capacity: int) -> None: ...

    @property
    def capacity(self) -> int: ...

    @capacity.setter
    def capacity(self, value: int) -> None: ...

    @property
    def size(self) -> int: ...

    @size.setter
    def size(self, value: int) -> None: ...

    def get_capacity(self) -> int: ...

    def get_size(self) -> int: ...
